version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.back4app
    ports:
      - '80:80'
    environment:
      - PARSE_SERVER_APPLICATION_ID=${PARSE_SERVER_APPLICATION_ID}
      - PARSE_SERVER_MASTER_KEY=${PARSE_SERVER_MASTER_KEY}